name: we_ready_app
description: "We Ready - SaaS Wedding Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Remote Data Source
  dio: ^5.4.1
  http: ^1.2.2
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  intl: ^0.20.2

  # Build Generator
  build_runner: ^2.4.11

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Hive Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

  # Dependency Injection
  get_it: ^7.6.7

  # Path Provider
  path_provider: ^2.1.2
  provider: ^6.1.1

  # Bloc State Management
  flutter_bloc: ^8.1.4

  # For Testing Class
  equatable: ^2.0.5

  # UUID
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Chart_Increasing.png
    - assets/icons/Check_Mark_Button.png
    - assets/icons/Cross_Mark.png
    - assets/icons/Envelope.png
    - assets/icons/Family_Man_Woman_Boy.png
    - assets/icons/Family_Man_Woman_Girl_Boy.png
    - assets/icons/High_Heeled_Shoe.png
    - assets/icons/Hourglass_Done.png
    - assets/icons/Large_Green_Circle.png
    - assets/icons/Megaphone.png
    - assets/icons/Money_Bag.png
    - assets/icons/Money_With_Wings.png
    - assets/icons/Page_Facing_Up.png
    - assets/icons/Party_Popper.png
    - assets/icons/Person_In_Tuxedo_Light_Skin_Tone.png
    - assets/icons/Raising_Hands_Light_Skin_Tone.png
    - assets/icons/Spiral_Calendar.png
    - assets/icons/White_Circle.png
    - assets/icons/Woman_And_Man_Holding_Hands_Medium_Light_Skin_Tone.png
    - assets/icons/Woman_With_Veil_Light_Skin_Tone.png


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
          weight: 800