name: we_ready_app
description: "We Ready - SaaS Wedding Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Remote Data Source
  dio: ^5.4.1
  http: ^1.2.2
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Build Generator
  build_runner: ^2.4.11

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Dependency Injection
  get_it: ^7.6.7

  # Path Provider
  path_provider: ^2.1.2
  provider: ^6.1.1

  # Bloc State Management
  flutter_bloc: ^8.1.4

  # For Testing Class
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.otf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
          weight: 800